### ISSUE TITLE
bootstraping sdn-ixp

### ISSUE THREAD

**Issue by dkalog** [sdn-ixp/sdx#12]
I am trying to fire-up the sdn-ixp according to the installation instructions of https://github.com/sdn-ixp/sdx meaning the https://docs.google.com/document/d/1wLF3RZEwMCRioyvaVl73kjXeNgqIaA3LfUlGsI2mkb4/edit . However when I try to start the pyretic SDX controller, I get the following error message :
mininet@mininet-vm:~/pyretic$ pyretic.py -v high pyretic.sdx.main
Must be a valid python module
e.g, full module name,
     no .py suffix,
     located on the system PYTHONPATH

However my PYTHONPATH is  mininet@mininet-vm:~/pyretic$ echo $PYTHONPATH
/home/mininet/pyretic:/home/mininet/pyretic/pyretic/sdx:/home/mininet/mininet:/home/mininet/pox

Any hints ?

**Comment by hammadmazhar1** [comment]
Im seeing the same problem. Some help would be appreciated

**Comment by hammadmazhar1** [comment]
i seem to have gotten past here by removing the pyretic directory, cloning the one from www.github.com/frenetic-lang/pyretic,  and then applying the checkout as mentioned in the document. But now I get this:
** Creating Quagga network topology
** Using Mininet Extended (MiniNExT) Handler
*** Creating network
*** Adding controller
*** Adding hosts:
Traceback (most recent call last):
  File "/home/mininet/pyretic/pyretic/sdx/examples/app_specific_peering_inboundTE/mininet/sdx_mininext.py", line 136, in <module>
    startNetwork()
  File "/home/mininet/pyretic/pyretic/sdx/examples/app_specific_peering_inboundTE/mininet/sdx_mininext.py", line 109, in startNetwork
    controller=lambda name: RemoteController( name, ip='127.0.0.1' ),listenPort=6633)
  File "build/bdist.linux-i686/egg/mininext/net.py", line 16, in __init__
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 163, in __init__
    self.build()
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 315, in build
    self.buildFromTopo( self.topo )
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 289, in buildFromTopo
    self.addHost( hostName, **topo.nodeInfo( hostName ) )
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 185, in addHost
    h = cls( name, **defaults )
  File "build/bdist.linux-i686/egg/mininext/node.py", line 53, in __init__
  File "/usr/lib/python2.7/dist-packages/mininet/node.py", line 92, in __init__
    self.startShell()
  File "build/bdist.linux-i686/egg/mininext/node.py", line 103, in startShell
Exception: Unable to determine shell's PID

**Comment by agupta13** [comment]
We will dive into this issue. Thanks for letting us know.
